/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Register`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/conductor`; params?: Router.UnknownInputParams; } | { pathname: `/usuario/historial`; params?: Router.UnknownInputParams; } | { pathname: `/usuario`; params?: Router.UnknownInputParams; } | { pathname: `/usuario/miViaje`; params?: Router.UnknownInputParams; } | { pathname: `/usuario/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/usuario/solicitudes`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/conductor`; params?: Router.UnknownOutputParams; } | { pathname: `/usuario/historial`; params?: Router.UnknownOutputParams; } | { pathname: `/usuario`; params?: Router.UnknownOutputParams; } | { pathname: `/usuario/miViaje`; params?: Router.UnknownOutputParams; } | { pathname: `/usuario/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/usuario/solicitudes`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/Register${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `/conductor${`?${string}` | `#${string}` | ''}` | `/usuario/historial${`?${string}` | `#${string}` | ''}` | `/usuario${`?${string}` | `#${string}` | ''}` | `/usuario/miViaje${`?${string}` | `#${string}` | ''}` | `/usuario/perfil${`?${string}` | `#${string}` | ''}` | `/usuario/solicitudes${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Register`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/conductor`; params?: Router.UnknownInputParams; } | { pathname: `/usuario/historial`; params?: Router.UnknownInputParams; } | { pathname: `/usuario`; params?: Router.UnknownInputParams; } | { pathname: `/usuario/miViaje`; params?: Router.UnknownInputParams; } | { pathname: `/usuario/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/usuario/solicitudes`; params?: Router.UnknownInputParams; };
    }
  }
}
